pipeline {
   agent any
   environment {
     SERVICE_NAME = "ms-qdc"
	 DOCKER_REGISTRY = "localhost:3200"
	 NAMESPACE = "platform-app"
   }

   stages {
     stage('Preparation') {
        steps {
           cleanWs()
           git credentialsId: '63978329-a1ea-4d66-9048-4f19d66444f5', url: "https://gitlab.com/tmcp/${SERVICE_NAME}.git"
        }
   }
  
  stage('Build Image') {
     steps {
	   sh 'docker build --build-arg DOCKER_ENV=dev . -t localhost:32000/${SERVICE_NAME}'
     }
  } 
  
  stage('Artifact') {
     steps {
       sh 'docker push localhost:32000/${SERVICE_NAME}'
     }
  } 

  //for first deployment cmd : kubectl apply -f deploy.yaml -n  ${NAMESPACE}
  stage('Deploy to Cluster') {
    steps {
      sh 'microk8s kubectl rollout restart deployment ${SERVICE_NAME} -n ${NAMESPACE}'
	  //sh 'envsubst < ${WORKSPACE}/deploy.yaml | microk8s kubectl apply -f - -n ${NAMESPACE}'
    }
  }
  
  stage('Cleanup') {
      steps{
        //sh "docker rmi localhost:32000/${SERVICE_NAME}"
		sh "docker rmi `docker images --filter dangling=true -q`"
      }
 }
}
}